1st try
RuslanMalyugin/cipherator pull request #2
Opened 2020-04-21 22:34 UTC by RuslanMalyugin

2020-04-21 22:40 UTC, WokinShopash requested changes

2020-04-21 22:40 UTC, WokinShopash commented on encryptor.py
> +parser = argparse.ArgumentParser()
При таком подходе в режимах будут пристутствовать незначащщие аргументы, что приведет к запутыванию пользователя.
Лучше разобрать аргументы через subparsers

2020-04-21 22:40 UTC, WokinShopash commented on encryptor.py
> +        return chr((ord(digit) - ord(letter) + int(slide) * mode) % 26 + ord(letter))
Решение с chr/ord - нерасширяемо. Стоит переписать на фиксированный алфавит

2020-04-21 22:40 UTC, WokinShopash commented on encryptor.py
> +def one_digit_cipherator(slide, digit, mode, letter, cipher, counter):
letter - не очень удачное имя для переменной в том смысле, в котором она тут используется

2020-04-21 22:40 UTC, WokinShopash commented on encryptor.py
> +        if arguments.output_file:
Дублирование кода вывода, унести в функцию

2020-04-28 21:33 UTC, RuslanMalyugin commented on encryptor.py
> +        return chr((ord(digit) - ord(letter) + int(slide) * mode) % 26 + ord(letter))
Если я сделаю словарь и буду по нему смотреть, это будет нормально?

2020-05-03 19:46 UTC, WokinShopash commented on encryptor.py
> +        return chr((ord(digit) - ord(letter) + int(slide) * mode) % 26 + ord(letter))
Да.

2020-05-03 19:57 UTC, WokinShopash requested changes

2020-05-03 19:57 UTC, WokinShopash commented on encryptor.py
> +def hacking (arguments) :
Проблел между названием и аргументами лишний

2020-05-03 19:57 UTC, WokinShopash commented on encryptor.py
> +    new_file = open(file, 'w')
Надо сделать под  with, иначе небезопасно

2020-05-03 19:57 UTC, WokinShopash commented on encryptor.py
> +def coding(input_, slide_, action_, cipher_):
зачем нижние подчеркивания?

2020-05-03 19:57 UTC, WokinShopash commented on encryptor.py
> +            result += one_digit_cipherator(slide_, i, action_, letter, cipher_, counter)
Конкатенация делается через копирование, что порождает квадратичную ассимпотику.
Используй str.join

2020-05-03 19:57 UTC, WokinShopash commented on encryptor.py
> +    letters_counter = {}
используй defaultdict или Counter

2020-05-03 19:57 UTC, WokinShopash commented on encryptor.py
> +    text_tmp = text_to_train.lower()
Лишний проход по тексту

2020-05-03 19:57 UTC, WokinShopash commented on encryptor.py
> +    for i in range(26):
магическая константа

2020-05-03 19:57 UTC, WokinShopash commented on encryptor.py
> +        list_for_hack.append(abs(ord(model_list[i][0]) - ord(coded_list[i][0])))
Достаточно странный алгоритм, не такой, как в условии, кажется, он очень чувствителен к колебаниям на маленьких частотах.

2020-05-10 18:40 UTC, RuslanMalyugin commented on encryptor.py
> +        list_for_hack.append(abs(ord(model_list[i][0]) - ord(coded_list[i][0])))
Кажется, этот алгоритм более точный, потому что он смотрит много символов и сравнивает.(По крайней мере на немаленьких текстах работает отлично)

2020-05-12 14:39 UTC, WokinShopash commented on encryptor.py
> +        list_for_hack.append(abs(ord(model_list[i][0]) - ord(coded_list[i][0])))
"Смотрит много символов и сравнивает" можно сказать примерно про любой алгоритм.
Я верю, что он работает, но на очень больших текстах с очень точным соблюдением соблюдением.

Давай все-таки сделаем взлом по условию.

2020-05-12 14:39 UTC, WokinShopash commented on encryptor.py
> +        list_for_hack.append(abs(ord(model_list[i][0]) - ord(coded_list[i][0])))
Либо приведи какую-нибудь репрезентативную выборку текстов и докажи, что твой алгоритм более точный :)

2020-05-23 21:03 UTC, WokinShopash requested changes

2020-05-23 21:03 UTC, WokinShopash commented on encryptor.py
> +            result = ''.join([result, one_digit_cipherator(slide, i, action, letter, cipher, counter)])
Это что-то странное, речь была о том, чтобы в цикле добавить в предварительно созданный список все символы, а вне цикла одним join-ом их собрать из них итоговую строку

2020-05-23 21:03 UTC, WokinShopash commented on encryptor.py
> +        if size == "a":
Снова магическая константа.
Ну и странное название переменной.
size - это какой-то размер (т.е. число), но никак не строка

2020-05-23 21:03 UTC, WokinShopash commented on encryptor.py
> +    text_tmp = text_to_train.lower()
Не исправлено

2020-05-23 21:03 UTC, WokinShopash commented on encryptor.py
> +    texting(parser_arguments)
Следуя логике соседних функций, тут должно быть training

2020-05-23 21:03 UTC, WokinShopash commented on encryptor.py
> +        if size == "a":
В одном файле/проекте используй один и тот же стиль кавычек (или только одинарные, или только двойные). Исключение допустимо, только если строка содержит внутри себя такой же тип кавычек.

2020-05-23 21:03 UTC, WokinShopash commented on encryptor.py
> +    letters_counter = {a: 0 for a in string.ascii_lowercase}
Все еще тут просится defaultdict/Counter

2020-05-25 21:05 UTC, WokinShopash requested changes

2020-05-25 21:05 UTC, WokinShopash commented on encryptor.py
> +def train(text_to_train):
train падает

2020-05-26 08:52 UTC, WokinShopash commented
Зачтено.

2021-03-31 17:40 UTC, closed without merging